app:
  id: my-sb1

server:
  port: 13840
  servlet:
    context-path: /my-sb1
spring:
    application:
      name: my-sb1

##eureka注册中心
eureka:
  client:
    serviceUrl:
       defaultZone: http://127.0.0.1:13910/eureka
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15

##appollo配置中心
apollo:
  bootstrap:
    enabled: true
    namespaces: application,business
    eagerLoad:
      enabled: true

#mybatis 配置
mybatis:
  mapper-locations: classpath*:mybatis/mappers/**/*Mapper.xml
  config-location: classpath:config/sqlMapConfig.xml

feign:
  hystrix:
    enabled:true

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds:20000

ribbon:
  ReadTimeout: 100000
  ConnectTimeout: 100000
